export const SET_USER_AUTHENTICATION = "SET_USER_AUTHENTICATION";
export const USER_LOGOUT = "USER_LOGOUT";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const ADD_NEW_QUESTION = "ADD_NEW_QUESTION";
export const ADD_NEW_QUESTION_ANSWER = "ADD_NEW_QUESTION_ANSWER";

export const GET_USERS = "GET_USERS";
export const ADD_NEW_USER_ANSWER = "ADD_NEW_USER_ANSWER";
export const ADD_NEW_USER_QUESTION = "ADD_NEW_USER_QUESTION";
